### ISSUE TITLE
Memory warnings & crashes

### ISSUE THREAD

**Issue by r3econ** [gdavis/FGallery-iPhone#13]
So, I loaded 180 images (about 500Kb each). And after I viewed about 15 app crashed (<Warning>: Memory level is not normal (63%).).

I guess the memory handling is not done in a right way.

**Comment by gdavis** [comment]
Are you loading the images into memory before FGallery requests them?

**Comment by gdavis** [comment]
And are you loading from the network or disk?

**Comment by ghost** [comment]
I experienced the same issue by loading multiple images from the web. just added additional image URLs to the networkImages NSArray in your example. Memory Usage is growing fast and then the App crashes Is there another way to handle a high amount of pictures loaded from the web?

**Comment by ernani** [comment]
I am having the exact same issue, I am testing within an iPhone 3Gs with iOS 5.1.1.

It seems it doesn't like much about the preloading threads, after some usage, it crashes and the available memory gets knocked out.

UPDATED: If using this component on a UINavigationController, I was able to manage the memory by handling the cleanup of images and threads on viewDidDisappear, this way my memory keeps fresh on each viewWillAppear.

**Comment by ghost** [comment]
How did you do that? Are you using the code from the memory warning method? 
thanks

**Comment by ernani** [comment]
I don't have the access to the code for now but will keep your notificaiton
here on my email and will update the message later with the details on my
code, sounds good?

Cheers

**Comment by ghw311** [comment]
Application crashes on loading too many images in iPhone，why?

**Comment by ernani** [comment]
It depends on the size of the images and also the amount of images you are displaying in a grid, also I'd recommend optimizing the methods I've suggested up above.
