### ISSUE TITLE
How to implement AutoRotate?

### ISSUE THREAD

**Issue by hieplt** [gdavis/FGallery-iPhone#17]
Hi,

I see that the gallery's supported autorotating quite well. But I failed to implement this for the Root View Controller. Can you give me some help?

Thanks in advance!

**Comment by gdavis** [comment]
Consult Apple's Cocoa Programming Documentation to figure out how to support rotations.

**Comment by hieplt** [comment]
I spent my day working around this problem. I read documents about rotation supporting and had implemented it ok with some simple projects, but when applying them to fgallery I can't make it work.
