### ISSUE TITLE
Rotation with FGallery

### ISSUE THREAD

**Issue by JMattos** [gdavis/FGallery-iPhone#22]
Hi thereI was wondering why you chose to override rotation in the FGalleryViewController. The comment is

/**
-  This section overrides the auto-rotate methods for UINaviationController and UITabBarController 
-  to allow the tab bar to rotate only when a FGalleryController is the visible controller. Sweet.
  */

Just curious.

**Comment by gdavis** [comment]
The intent is to allow the FGallery to rotate to all interface orientations no matter what the parent view controller has set for its own allowed orientations. This is particularly useful when pushing the FGallery into a UINavigationController stack where a view controller in the hierarchy does not allow a particular rotation. When this happens, FGallery would not be able to rotate when viewed. By overriding these methods at the UINavigationController and UITabBarController levels, we are allowed a "first-check" (i.e. the first view controller to respond) which allows us to return YES for all orientations when an FGallery is visible. This keeps FGallery rotating at all orientations no matter what.
