### ISSUE TITLE
Using the library with translucent navbar leads to thumbnails positioning problems

### ISSUE THREAD

**Issue by apow** [gdavis/FGallery-iPhone#3]
Using the library with a translucent navbar leads to incorrectly arranged images in the thumbnail view. Seems to be a problem in - (void)arrangeThumbs", perhaps smth like "float dy = self.navigationController.navigationBar.bounds.size.height" might make it behave a bit better (does not fully resolve the issue though).

**Comment by gdavis** [comment]
Implemented.
