### ISSUE TITLE
ARC version

### ISSUE THREAD

**Issue by kasperfn** [gdavis/FGallery-iPhone#35]
Does anybody have a FGallery project working with ARC? :) 

(not -fno-objc-arc flag for files)

**Comment by kasperfn** [comment]
Nvm. I did it on my own. Have a nice day

**Comment by apoorvnarang** [comment]
How did you do it? Can you share the ARC version code please?

**Comment by kasperfn** [comment]
Just remove release, autorelease

and where 'NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];' is - make for example:  

```
    @autoreleasepool {
    NSString *path = [NSString stringWithFormat:@"%@/%@", [[NSBundle mainBundle] bundlePath], _fullsizeUrl];
    _fullsize = [UIImage imageWithContentsOfFile:path];

    _hasFullsizeLoaded = YES;
    _isFullsizeLoading = NO;

    [self performSelectorOnMainThread:@selector(didLoadFullsize) withObject:nil waitUntilDone:YES];
} 
```

**Comment by mdikov** [comment]
I used the conversion tool in Xcode and all works right away. 
The tool pretty much does the same.

**Comment by kasperfn** [comment]
@mdikov Let him learn it the hard way ;)

**Comment by craigreilly** [comment]
ahh - thank you for this... much better functionality now with my 6 galleries.
