### ISSUE TITLE
"See All" / "Done" rightBarButtonItem button customization

### ISSUE THREAD

**Issue by apow** [gdavis/FGallery-iPhone#4]
Would be good to have a consistent way to customize initial state of the library, with ability to start in both photo & thumbnail views (hiding the button in thumbnail view would be cool as well :). Not as hard to workaround these, but  would be nice to have support for these kind of things directly within the library.

**Comment by gdavis** [comment]
Added support for hiding the right navigation bar button through a new useThumbnailView property.
