### ISSUE TITLE
rotation resize issue

### ISSUE THREAD

**Issue by amitbattan** [gdavis/FGallery-iPhone#6]
function `layoutViews` is not calling from the function `- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context`

I try to call `layoutViews` method in the `willRotateToInterfaceOrientation` delegate but in this case design becime distorted.

**Comment by gdavis** [comment]
I don't know why you'd be seeing this. I just ran the project and put an NSLog in both the observeValueForKeyPath method and layoutViews and they are being called just fine. There must be an issue with how you are implementing the view controller. I would need more information in how you are presenting the view controller to assist you.

**Comment by amitbattan** [comment]
I am using it with phonegap like this.

```
    if(galleryController == NULL)
    {
        galleryController = [[FGalleryViewController alloc] initWithPhotoSource:self];
    }

    PhoneGapViewController* cont = (PhoneGapViewController*)[ super appViewController ];
       [cont presentModalViewController:galleryController animated:YES ];
```

Yes in your code it is working fine but not in mine.

**Comment by gdavis** [comment]
I'm not familiar with PhoneGap's view controller system. The apple view controllers automatically adjust the frame of the view of the FGalleryViewController which is what triggers the KVO method calls. If these controllers do not do that, you'll have to manually implement the changing of the gallery's view. That's about all the help I can give you.
