### ISSUE TITLE
Autoresizing of imageview in scrollview (issue)

### ISSUE THREAD

**Issue by paresh-navadiya** [gdavis/FGallery-iPhone#60]
![ios simulator screen shot 29-dec-2014 3 00 28 am](https://cloud.githubusercontent.com/assets/1125736/5566978/e5307634-8f06-11e4-9e98-912a598fe334.png)
![ios simulator screen shot 29-dec-2014 3 00 33 am](https://cloud.githubusercontent.com/assets/1125736/5566979/e610a93e-8f06-11e4-8a6d-b38ccbf785f9.png)
![ios simulator screen shot 29-dec-2014 3 00 37 am](https://cloud.githubusercontent.com/assets/1125736/5566981/ed00616c-8f06-11e4-886b-9619db9b30e9.png)

**Comment by paresh-navadiya** [comment]
<b>Replace below methods with new one : <b>
- (void)positionInnerContainer
  {
  CGRect innerContainerRect;
  
  innerContainerRect = CGRectMake( 0.0,0.0, _container.frame.size.width,_container.frame.size.height);
  
  _innerContainer.frame = innerContainerRect;
  }
- (void)positionScroller
  {
  CGRect scrollerRect;
  
  scrollerRect = CGRectMake( 0.0,0.0, _innerContainer.frame.size.width,_innerContainer.frame.size.height-kToolbarHeight);
  _scroller.frame = scrollerRect;
  }
- (void)positionToolbar
  {
  _toolbar.frame = CGRectMake( 0, _scroller.frame.size.height, _scroller.frame.size.width, kToolbarHeight );
  }

<b> Also replace UINavigationController (FGallery) category if using UINavigationController</b>

@implementation UINavigationController (FGallery)
- (BOOL)shouldAutorotate
  {
  return YES;
  }
- (NSUInteger)supportedInterfaceOrientations
  {
  return UIInterfaceOrientationMaskAll;
  }
- (void)willRotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration
  {
  // see if the current controller in the stack is a gallery
  if([self.visibleViewController isKindOfClass:[FGalleryViewController class]])
  {
      FGalleryViewController _galleryController = (FGalleryViewController_)self.visibleViewController;
      [galleryController resetImageViewZoomLevels];
  }
  }

-(void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator
{
    // see if the current controller in the stack is a gallery
    if([self.visibleViewController isKindOfClass:[FGalleryViewController class]])
    {
        FGalleryViewController _galleryController = (FGalleryViewController_)self.visibleViewController;
        [galleryController resetImageViewZoomLevels];
    }
}

**Comment by sergisolanellas** [comment]
@safecase123 , great answer! I had a problem with iPad and this code solve it! Many thanks!

This code should be in the main project :)
