### ISSUE TITLE
Start in thumbnail view

### ISSUE THREAD

**Issue by BryanWilkins** [gdavis/FGallery-iPhone#9]
Is there a proper way to start in thumbnail view? Instead of the default view and then pressing show all.

**Comment by gdavis** [comment]
Not currently. You can look at the handleSeeAllTouch method in the FGalleryViewController and refactor that into a public method and call that when entering the view. I'll see about adding this as a feature.

**Comment by BryanWilkins** [comment]
Wow thanks!  Really awesome control you have.  Solid architecture.  Keep up the good work.
